USE ZOT;

DROP TABLE T_ZOT_COST;

CREATE TABLE T_ZOT_COST 
(
COST_ID VARCHAR(50) NOT NULL PRIMARY KEY,
COST_TYPE VARCHAR(20) NOT NULL,
COST_SUBTYPE VARCHAR(20) NOT NULL,
REMARK VARCHAR(512),
COST_AMOUNT FLOAT(10,1),
COST_OPERATOR VARCHAR(20),
COST_TIME TIMESTAMP,
CREATE_TIME TIMESTAMP
);

COMMIT;